import pickle as pkl
from utils.text_analyzer import TextStats
from crackers.mono import crack_mono
from utils.dictionary import Dictionary


def identify_ciphers(stats, dictionary):
    print("IC of ciphertext is " + str(stats.ic) + " , IC of dictionary is " + str(dictionary.ic))
    if (abs(stats.ic - dictionary.ic)) < 0.4:
        print("Monoalphabetic substitution was likely used")
        crack_mono(stats, dictionary)
    else:
        print("Monoalphabetic substitution was not used")


if __name__ == "__main__":
    texts = ["RBLMRRMGELPQBMULQGMKLUFTGCMIJHMULTKBCQHCIURBMRQCRBLQMCURJHMPCIMWLPLAJCIARJFCVLCIRJWIILMPFJRQJSJRBLPBJTQLQ"
             "CIMBJTQLWBLPLWLGMIOLQMSLQJHLRCHLFMRLPRBLKJFCGLRJFUMFFRBLHLHOLPQJSRBLSMHCFYRBMRRBLYBMUTIGJVLPLUHJPLKFJRQRB"
             "CQRCHLRJECUIMKACTFCMIMMIUFTGCMIJQQJIMFLQQMIUPJ",
             "ABCVTBAWHDAXJQGOENKRAUOIZUSRDYENMHTTZAZXHUBLFVHFGRJIJTGFTSLVGUFDZCNGWMQVUGUSZTATBGMAJYENEZKHOOHERIDYKSHFF"
             "WLMUXGMXKTUXMDTHNRQHDPVRQBBMGFCBFDMCFEKMFMDYDVGODNAOFVOZXSIXXRFWLSBNBPDMTUBGTTOAQASMGKOSUSZTATBGOZSAOYWTU"
             "DYUPVWIWHTUXHTDBGUMCRIOEPHABPUY",
             "ACRVNEHEHOAEHRONNREXLUORIMSDTFFRREIARESXASCKAODOSERSTEYNDEYRSFIELCBEPCNHAWFAUAVILRWOTBANTINNEVHEEVYSWIHDE"
             "LASRAIIIAABNTEOEOEFNUTAILAOLSSLDHRU",
             "GLIAXQKERPVYLIJCIILWIPIREJVSHVXIXSWMTMEVWMLRXRIXXJROXGISSPRIIXGGEEQVRCGHVLLMXEEQAEIWJEMXIPVSEXMXMZWCWXOYW"
             "MREZIIYSLIWWRXXIRRRJSXFXCLIXYIMEYAIMTIW",
             "GGJSSYWMYYMFMPFNFYVJEJOYMVJNEMVMYQRETVWYIWEKGKMRPEEXVGIYTKJVVFJFJVYRVKYPYUWLJYPYJQRXVWEEXXEEMJEIEKMQVGEXK"
             "XMRMIPLXFVVVXOMXJUTNWJELJENJAGVYAMIEWRTJIGARVJEEEJXVMOVLVQVAGWOJFGFSGWRYGVJVX",
             "HHIEETWSTFDETERSKKTOJNGZNUGXOJUKSWHGHESTEUNESTUXMPQVQJSWZZLXQPVXRBFZFRAPJFGYAVQRMLHEANOOETWAGSTNKKKJIKCGY"
             "UKTCSNYDBAITTNSTRNNHOEIBCLIQBNBQMBMQDEDBFGEIBENAFLQPRBRHIHEINONJOMAHMRXUTKVZTSJGVUJNKRXLEFOIACFPERVENDXLA"
             "WZMUWCIVMMTBEXGFEGFRNEARJECNNX"]

    dict_dir = "/home/dita/ownCloud/Soutěže/Cracker/utils/"
    dict_langs = ["cs", "en"]

    dicts = []
    for lang in dict_langs:
        d = pkl.load(open(dict_dir + lang + ".pkl", "rb"))
        dicts.append(d)

    for ciphertext in texts:
        stats = TextStats(ciphertext)

        identify_ciphers(stats, dicts[1])
